version: '3'
services:
  app:
    env_file:
      - .env
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '6013:3000'
    container_name: potlock-backend